// 单词库种子数据：共 100 词，3 个级别
// 注意：id 1-30 与前端旧版本保持一致（localStorage 中的收藏/已学记录依赖 id）
export const wordsData = [
  // ===== 基础 Level 1 =====
  { id: 1, word: 'abandon', phonetic: '/əˈbændən/', meaning: 'v. 放弃，抛弃', level: 1, example: 'He abandoned his car in the snow.', exampleCn: '他把车丢在雪地里。' },
  { id: 2, word: 'benefit', phonetic: '/ˈbenɪfɪt/', meaning: 'n. 好处 v. 受益', level: 1, example: 'Exercise benefits your health.', exampleCn: '锻炼有益健康。' },
  { id: 3, word: 'curious', phonetic: '/ˈkjʊəriəs/', meaning: 'adj. 好奇的', level: 1, example: 'The child was curious about everything.', exampleCn: '这个孩子对一切都很好奇。' },
  { id: 4, word: 'decide', phonetic: '/dɪˈsaɪd/', meaning: 'v. 决定', level: 1, example: 'She decided to study abroad.', exampleCn: '她决定出国留学。' },
  { id: 5, word: 'energy', phonetic: '/ˈenədʒi/', meaning: 'n. 能量，精力', level: 1, example: 'He is full of energy every morning.', exampleCn: '他每天早上都精力充沛。' },
  { id: 6, word: 'famous', phonetic: '/ˈfeɪməs/', meaning: 'adj. 著名的', level: 1, example: 'The city is famous for its food.', exampleCn: '这座城市以美食闻名。' },
  { id: 7, word: 'gather', phonetic: '/ˈɡæðər/', meaning: 'v. 聚集，收集', level: 1, example: 'We gathered around the campfire.', exampleCn: '我们围着篝火聚集。' },
  { id: 8, word: 'honest', phonetic: '/ˈɒnɪst/', meaning: 'adj. 诚实的', level: 1, example: 'He is an honest man.', exampleCn: '他是个诚实的人。' },
  { id: 9, word: 'improve', phonetic: '/ɪmˈpruːv/', meaning: 'v. 改进，提高', level: 1, example: 'I want to improve my English.', exampleCn: '我想提高我的英语水平。' },
  { id: 10, word: 'journey', phonetic: '/ˈdʒɜːni/', meaning: 'n. 旅行，旅程', level: 1, example: 'Life is a long journey.', exampleCn: '人生是一场漫长的旅行。' },
  { id: 31, word: 'ability', phonetic: '/əˈbɪləti/', meaning: 'n. 能力，才能', level: 1, example: 'She has the ability to solve hard problems.', exampleCn: '她有解决难题的能力。' },
  { id: 32, word: 'borrow', phonetic: '/ˈbɒrəʊ/', meaning: 'v. 借，借入', level: 1, example: 'May I borrow your pen?', exampleCn: '我可以借用你的笔吗？' },
  { id: 33, word: 'brave', phonetic: '/breɪv/', meaning: 'adj. 勇敢的', level: 1, example: 'It was brave of him to admit the mistake.', exampleCn: '他能承认错误非常勇敢。' },
  { id: 34, word: 'comfort', phonetic: '/ˈkʌmfət/', meaning: 'n. 安慰 v. 安慰', level: 1, example: 'Her words gave me great comfort.', exampleCn: '她的话给了我极大的安慰。' },
  { id: 35, word: 'deliver', phonetic: '/dɪˈlɪvər/', meaning: 'v. 递送，投递', level: 1, example: 'The postman delivers letters every morning.', exampleCn: '邮差每天早上送信。' },
  { id: 36, word: 'examine', phonetic: '/ɪɡˈzæmɪn/', meaning: 'v. 检查，测验', level: 1, example: 'The doctor examined the patient carefully.', exampleCn: '医生仔细检查了病人。' },
  { id: 37, word: 'freedom', phonetic: '/ˈfriːdəm/', meaning: 'n. 自由', level: 1, example: 'They fought for freedom.', exampleCn: '他们为自由而战。' },
  { id: 38, word: 'gentle', phonetic: '/ˈdʒentl/', meaning: 'adj. 温和的，轻柔的', level: 1, example: 'She spoke in a gentle voice.', exampleCn: '她说话的声音很温柔。' },
  { id: 39, word: 'habit', phonetic: '/ˈhæbɪt/', meaning: 'n. 习惯', level: 1, example: 'Reading is a good habit.', exampleCn: '阅读是一个好习惯。' },
  { id: 40, word: 'imagine', phonetic: '/ɪˈmædʒɪn/', meaning: 'v. 想象', level: 1, example: 'Imagine life without the Internet.', exampleCn: '想象一下没有互联网的生活。' },
  { id: 41, word: 'island', phonetic: '/ˈaɪlənd/', meaning: 'n. 岛屿', level: 1, example: 'We spent our holiday on a small island.', exampleCn: '我们在一个小岛上度假。' },
  { id: 42, word: 'knowledge', phonetic: '/ˈnɒlɪdʒ/', meaning: 'n. 知识', level: 1, example: 'Knowledge is power.', exampleCn: '知识就是力量。' },
  { id: 43, word: 'laugh', phonetic: '/lɑːf/', meaning: 'v./n. 笑', level: 1, example: 'The joke made everyone laugh.', exampleCn: '这个笑话把大家都逗笑了。' },
  { id: 44, word: 'medicine', phonetic: '/ˈmedsn/', meaning: 'n. 医学，药', level: 1, example: 'Take this medicine twice a day.', exampleCn: '这种药一天服两次。' },
  { id: 45, word: 'natural', phonetic: '/ˈnætʃrəl/', meaning: 'adj. 自然的', level: 1, example: 'Natural food is good for your health.', exampleCn: '天然食物对健康有益。' },
  { id: 46, word: 'opinion', phonetic: '/əˈpɪnjən/', meaning: 'n. 意见，观点', level: 1, example: 'In my opinion, the movie is great.', exampleCn: '在我看来，这部电影很棒。' },
  { id: 47, word: 'patient', phonetic: '/ˈpeɪʃnt/', meaning: 'adj. 耐心的 n. 病人', level: 1, example: 'Please be patient with beginners.', exampleCn: '请对初学者耐心一点。' },
  { id: 48, word: 'quality', phonetic: '/ˈkwɒləti/', meaning: 'n. 质量，品质', level: 1, example: 'Quality is more important than quantity.', exampleCn: '质量比数量更重要。' },
  { id: 49, word: 'realize', phonetic: '/ˈriːəlaɪz/', meaning: 'v. 意识到，实现', level: 1, example: "I didn't realize how late it was.", exampleCn: '我没意识到已经这么晚了。' },
  { id: 50, word: 'science', phonetic: '/ˈsaɪəns/', meaning: 'n. 科学', level: 1, example: 'Science has changed our lives.', exampleCn: '科学改变了我们的生活。' },
  { id: 51, word: 'trouble', phonetic: '/ˈtrʌbl/', meaning: 'n. 麻烦 v. 使烦恼', level: 1, example: "I'm sorry to trouble you.", exampleCn: '很抱歉打扰你。' },
  { id: 52, word: 'university', phonetic: '/ˌjuːnɪˈvɜːsəti/', meaning: 'n. 大学', level: 1, example: 'She studies at a famous university.', exampleCn: '她在一所著名的大学学习。' },
  { id: 53, word: 'village', phonetic: '/ˈvɪlɪdʒ/', meaning: 'n. 村庄', level: 1, example: 'My grandparents live in a quiet village.', exampleCn: '我的祖父母住在一个安静的村庄。' },
  { id: 54, word: 'weather', phonetic: '/ˈweðər/', meaning: 'n. 天气', level: 1, example: 'The weather is nice today.', exampleCn: '今天天气很好。' },

  // ===== 进阶 Level 2 =====
  { id: 11, word: 'achieve', phonetic: '/əˈtʃiːv/', meaning: 'v. 实现，达到', level: 2, example: 'You can achieve anything with hard work.', exampleCn: '努力工作你就能实现任何目标。' },
  { id: 12, word: 'brilliant', phonetic: '/ˈbrɪliənt/', meaning: 'adj. 杰出的，灿烂的', level: 2, example: 'She came up with a brilliant idea.', exampleCn: '她想到了一个绝妙的主意。' },
  { id: 13, word: 'challenge', phonetic: '/ˈtʃælɪndʒ/', meaning: 'n. 挑战 v. 向…挑战', level: 2, example: 'Learning a new language is a big challenge.', exampleCn: '学习一门新语言是个巨大的挑战。' },
  { id: 14, word: 'delicate', phonetic: '/ˈdelɪkət/', meaning: 'adj. 精致的，微妙的', level: 2, example: 'The vase is delicate and expensive.', exampleCn: '这个花瓶精致而昂贵。' },
  { id: 15, word: 'essential', phonetic: '/ɪˈsenʃl/', meaning: 'adj. 必要的，本质的', level: 2, example: 'Water is essential for life.', exampleCn: '水对生命必不可少。' },
  { id: 16, word: 'grateful', phonetic: '/ˈɡreɪtfl/', meaning: 'adj. 感激的', level: 2, example: 'I am grateful for your help.', exampleCn: '我很感激你的帮助。' },
  { id: 17, word: 'hesitate', phonetic: '/ˈhezɪteɪt/', meaning: 'v. 犹豫', level: 2, example: "Don't hesitate to ask questions.", exampleCn: '有问题尽管问，别犹豫。' },
  { id: 18, word: 'influence', phonetic: '/ˈɪnfluəns/', meaning: 'n./v. 影响', level: 2, example: 'Parents have a great influence on children.', exampleCn: '父母对孩子有很大的影响。' },
  { id: 19, word: 'maintain', phonetic: '/meɪnˈteɪn/', meaning: 'v. 维持，保养', level: 2, example: "It's hard to maintain a good habit.", exampleCn: '坚持一个好习惯很难。' },
  { id: 20, word: 'obstacle', phonetic: '/ˈɒbstəkl/', meaning: 'n. 障碍', level: 2, example: 'Fear is the biggest obstacle to success.', exampleCn: '恐惧是成功最大的障碍。' },
  { id: 55, word: 'ambition', phonetic: '/æmˈbɪʃn/', meaning: 'n. 雄心，抱负', level: 2, example: 'Her ambition is to become a doctor.', exampleCn: '她的抱负是成为一名医生。' },
  { id: 56, word: 'behavior', phonetic: '/bɪˈheɪvjər/', meaning: 'n. 行为，举止', level: 2, example: 'His behavior at the party surprised everyone.', exampleCn: '他在聚会上的举止让大家都感到惊讶。' },
  { id: 57, word: 'campaign', phonetic: '/kæmˈpeɪn/', meaning: 'n. 运动，活动', level: 2, example: 'They started a campaign to protect animals.', exampleCn: '他们发起了一场保护动物的运动。' },
  { id: 58, word: 'decline', phonetic: '/dɪˈklaɪn/', meaning: 'v. 下降，婉拒', level: 2, example: 'Sales began to decline last month.', exampleCn: '上个月销售额开始下降。' },
  { id: 59, word: 'efficient', phonetic: '/ɪˈfɪʃnt/', meaning: 'adj. 高效的', level: 2, example: 'She is an efficient worker.', exampleCn: '她是一位高效的员工。' },
  { id: 60, word: 'genuine', phonetic: '/ˈdʒenjuɪn/', meaning: 'adj. 真诚的，真正的', level: 2, example: 'He showed genuine interest in my ideas.', exampleCn: '他对我的想法表现出真诚的兴趣。' },
  { id: 61, word: 'guarantee', phonetic: '/ˌɡærənˈtiː/', meaning: 'n./v. 保证，担保', level: 2, example: 'Hard work does not guarantee success.', exampleCn: '努力工作并不能保证成功。' },
  { id: 62, word: 'harmony', phonetic: '/ˈhɑːməni/', meaning: 'n. 和谐', level: 2, example: 'We live in harmony with our neighbors.', exampleCn: '我们与邻居和谐相处。' },
  { id: 63, word: 'identity', phonetic: '/aɪˈdentəti/', meaning: 'n. 身份，特性', level: 2, example: 'The police checked his identity.', exampleCn: '警察核对了他的身份。' },
  { id: 64, word: 'landscape', phonetic: '/ˈlændskeɪp/', meaning: 'n. 风景，景色', level: 2, example: 'The landscape around the lake is beautiful.', exampleCn: '湖边的风景很美。' },
  { id: 65, word: 'mysterious', phonetic: '/mɪˈstɪəriəs/', meaning: 'adj. 神秘的', level: 2, example: 'The old house has a mysterious history.', exampleCn: '这座老房子有一段神秘的历史。' },
  { id: 66, word: 'negotiate', phonetic: '/nɪˈɡəʊʃieɪt/', meaning: 'v. 谈判，协商', level: 2, example: 'The two sides agreed to negotiate.', exampleCn: '双方同意进行谈判。' },
  { id: 67, word: 'permanent', phonetic: '/ˈpɜːmənənt/', meaning: 'adj. 永久的', level: 2, example: 'The accident left a permanent scar.', exampleCn: '这次事故留下了永久性的伤疤。' },
  { id: 68, word: 'remarkable', phonetic: '/rɪˈmɑːkəbl/', meaning: 'adj. 非凡的，显著的', level: 2, example: 'She made remarkable progress this term.', exampleCn: '她这学期进步显著。' },
  { id: 69, word: 'significance', phonetic: '/sɪɡˈnɪfɪkəns/', meaning: 'n. 重要性，意义', level: 2, example: 'This discovery is of great significance.', exampleCn: '这一发现意义重大。' },
  { id: 70, word: 'temporary', phonetic: '/ˈtemprəri/', meaning: 'adj. 暂时的', level: 2, example: 'They found a temporary solution.', exampleCn: '他们找到了一个临时解决方案。' },
  { id: 71, word: 'universal', phonetic: '/ˌjuːnɪˈvɜːsl/', meaning: 'adj. 普遍的，通用的', level: 2, example: 'Music is a universal language.', exampleCn: '音乐是一种通用语言。' },
  { id: 72, word: 'withdraw', phonetic: '/wɪðˈdrɔː/', meaning: 'v. 撤回，取款', level: 2, example: 'He withdrew some money from the bank.', exampleCn: '他从银行取了一些钱。' },
  { id: 73, word: 'accurate', phonetic: '/ˈækjərət/', meaning: 'adj. 准确的', level: 2, example: 'The weather forecast is not always accurate.', exampleCn: '天气预报并不总是准确的。' },
  { id: 74, word: 'collapse', phonetic: '/kəˈlæps/', meaning: 'v./n. 倒塌，崩溃', level: 2, example: 'The old bridge finally collapsed.', exampleCn: '那座老桥最终倒塌了。' },
  { id: 75, word: 'desperate', phonetic: '/ˈdespərət/', meaning: 'adj. 绝望的，拼命的', level: 2, example: 'They were desperate for water.', exampleCn: '他们极度渴望得到水。' },
  { id: 76, word: 'endeavor', phonetic: '/ɪnˈdevər/', meaning: 'n./v. 努力，尝试', level: 2, example: 'Please make every endeavor to arrive on time.', exampleCn: '请尽一切努力准时到达。' },
  { id: 77, word: 'financial', phonetic: '/faɪˈnænʃl/', meaning: 'adj. 金融的，财务的', level: 2, example: 'The company is in financial trouble.', exampleCn: '这家公司陷入了财务困境。' },

  // ===== 高阶 Level 3 =====
  { id: 21, word: 'accomplish', phonetic: '/əˈkʌmplɪʃ/', meaning: 'v. 完成，实现', level: 3, example: 'She accomplished the mission successfully.', exampleCn: '她成功完成了任务。' },
  { id: 22, word: 'comprehensive', phonetic: '/ˌkɒmprɪˈhensɪv/', meaning: 'adj. 全面的，综合的', level: 3, example: 'The report gives a comprehensive analysis.', exampleCn: '这份报告给出了全面的分析。' },
  { id: 23, word: 'distinguish', phonetic: '/dɪˈstɪŋɡwɪʃ/', meaning: 'v. 区分，辨别', level: 3, example: 'Can you distinguish the two sounds?', exampleCn: '你能区分这两个发音吗？' },
  { id: 24, word: 'elaborate', phonetic: '/ɪˈlæbərət/', meaning: 'adj. 精心的 v. 详细阐述', level: 3, example: 'Could you elaborate on your plan?', exampleCn: '你能详细说明一下你的计划吗？' },
  { id: 25, word: 'fundamental', phonetic: '/ˌfʌndəˈmentl/', meaning: 'adj. 基本的，根本的', level: 3, example: 'Freedom is a fundamental human right.', exampleCn: '自由是基本人权。' },
  { id: 26, word: 'hypothetical', phonetic: '/ˌhaɪpəˈθetɪkl/', meaning: 'adj. 假设的', level: 3, example: "That's a purely hypothetical question.", exampleCn: '那纯粹是个假设性的问题。' },
  { id: 27, word: 'inevitable', phonetic: '/ɪnˈevɪtəbl/', meaning: 'adj. 不可避免的', level: 3, example: 'Change is inevitable in life.', exampleCn: '生活中变化是不可避免的。' },
  { id: 28, word: 'legitimate', phonetic: '/lɪˈdʒɪtɪmət/', meaning: 'adj. 合法的，正当的', level: 3, example: 'He has a legitimate reason for being late.', exampleCn: '他迟到是有正当理由的。' },
  { id: 29, word: 'perspective', phonetic: '/pəˈspektɪv/', meaning: 'n. 观点，视角', level: 3, example: 'Try to see things from my perspective.', exampleCn: '试着从我的角度看问题。' },
  { id: 30, word: 'sophisticated', phonetic: '/səˈfɪstɪkeɪtɪd/', meaning: 'adj. 复杂的，精密的', level: 3, example: 'The software uses sophisticated algorithms.', exampleCn: '这个软件使用了复杂的算法。' },
  { id: 78, word: 'ambiguous', phonetic: '/æmˈbɪɡjuəs/', meaning: 'adj. 模棱两可的', level: 3, example: 'His answer was deliberately ambiguous.', exampleCn: '他的回答故意含糊其辞。' },
  { id: 79, word: 'coherent', phonetic: '/kəʊˈhɪərənt/', meaning: 'adj. 连贯的，条理清楚的', level: 3, example: 'She gave a coherent account of the accident.', exampleCn: '她对事故的叙述条理清晰。' },
  { id: 80, word: 'compromise', phonetic: '/ˈkɒmprəmaɪz/', meaning: 'n./v. 妥协，折中', level: 3, example: 'After a long discussion, they reached a compromise.', exampleCn: '经过长时间讨论，他们达成了妥协。' },
  { id: 81, word: 'dilemma', phonetic: '/dɪˈlemə/', meaning: 'n. 困境，进退两难', level: 3, example: 'She faced the dilemma of work or family.', exampleCn: '她面临着工作还是家庭的两难选择。' },
  { id: 82, word: 'eloquent', phonetic: '/ˈeləkwənt/', meaning: 'adj. 雄辩的，有说服力的', level: 3, example: 'He made an eloquent speech at the ceremony.', exampleCn: '他在典礼上发表了一场雄辩的演讲。' },
  { id: 83, word: 'implement', phonetic: '/ˈɪmplɪment/', meaning: 'v. 实施，执行', level: 3, example: 'The company implemented a new policy.', exampleCn: '公司实施了一项新政策。' },
  { id: 84, word: 'incentive', phonetic: '/ɪnˈsentɪv/', meaning: 'n. 激励，动机', level: 3, example: 'Bonuses are an incentive to work harder.', exampleCn: '奖金是更努力工作的激励。' },
  { id: 85, word: 'intricate', phonetic: '/ˈɪntrɪkət/', meaning: 'adj. 错综复杂的', level: 3, example: 'The watch has an intricate design.', exampleCn: '这块手表的设计错综复杂。' },
  { id: 86, word: 'mitigate', phonetic: '/ˈmɪtɪɡeɪt/', meaning: 'v. 减轻，缓和', level: 3, example: 'We must take action to mitigate the risk.', exampleCn: '我们必须采取行动减轻风险。' },
  { id: 87, word: 'negligible', phonetic: '/ˈneɡlɪdʒəbl/', meaning: 'adj. 微不足道的', level: 3, example: 'The difference in price is negligible.', exampleCn: '价格差异微不足道。' },
  { id: 88, word: 'paradox', phonetic: '/ˈpærədɒks/', meaning: 'n. 悖论，矛盾', level: 3, example: "It's a paradox that busy people find more time.", exampleCn: '忙碌的人反而更有时间，这是个悖论。' },
  { id: 89, word: 'prevalent', phonetic: '/ˈprevələnt/', meaning: 'adj. 普遍的，流行的', level: 3, example: 'Smartphones are prevalent among teenagers.', exampleCn: '智能手机在青少年中很普遍。' },
  { id: 90, word: 'profound', phonetic: '/prəˈfaʊnd/', meaning: 'adj. 深刻的，深远的', level: 3, example: 'The book had a profound influence on me.', exampleCn: '这本书对我产生了深远的影响。' },
  { id: 91, word: 'redundant', phonetic: '/rɪˈdʌndənt/', meaning: 'adj. 多余的，冗余的', level: 3, example: 'Delete the redundant words in the report.', exampleCn: '删掉报告中多余的词。' },
  { id: 92, word: 'skeptical', phonetic: '/ˈskeptɪkl/', meaning: 'adj. 怀疑的', level: 3, example: 'I am skeptical about his promise.', exampleCn: '我对他的承诺持怀疑态度。' },
  { id: 93, word: 'spontaneous', phonetic: '/spɒnˈteɪniəs/', meaning: 'adj. 自发的，自然的', level: 3, example: 'The audience broke into spontaneous applause.', exampleCn: '观众自发地鼓起掌来。' },
  { id: 94, word: 'subtle', phonetic: '/ˈsʌtl/', meaning: 'adj. 微妙的，细微的', level: 3, example: 'There is a subtle difference between the two words.', exampleCn: '这两个词之间有细微的差别。' },
  { id: 95, word: 'tremendous', phonetic: '/trəˈmendəs/', meaning: 'adj. 巨大的，惊人的', level: 3, example: 'The show was a tremendous success.', exampleCn: '这场演出取得了巨大的成功。' },
  { id: 96, word: 'versatile', phonetic: '/ˈvɜːsətaɪl/', meaning: 'adj. 多才多艺的，多用途的', level: 3, example: 'She is a versatile actress.', exampleCn: '她是一位多才多艺的演员。' },
  { id: 97, word: 'vigorous', phonetic: '/ˈvɪɡərəs/', meaning: 'adj. 有力的，精力充沛的', level: 3, example: 'He takes vigorous exercise every day.', exampleCn: '他每天进行剧烈运动。' },
  { id: 98, word: 'vulnerable', phonetic: '/ˈvʌlnərəbl/', meaning: 'adj. 脆弱的，易受伤的', level: 3, example: 'Young birds are vulnerable to predators.', exampleCn: '幼鸟容易受到捕食者的伤害。' },
  { id: 99, word: 'adequate', phonetic: '/ˈædɪkwət/', meaning: 'adj. 足够的，适当的', level: 3, example: 'Make sure the room has adequate light.', exampleCn: '确保房间有充足的光线。' },
  { id: 100, word: 'compelling', phonetic: '/kəmˈpelɪŋ/', meaning: 'adj. 引人注目的，有说服力的', level: 3, example: 'She made a compelling argument.', exampleCn: '她提出了一个令人信服的论点。' },
]

// 每日一句
export const sentencesData = [
  { id: 1, en: 'The best way to predict the future is to create it.', cn: '预测未来的最好方式就是创造未来。', author: 'Peter Drucker' },
  { id: 2, en: 'Practice makes perfect.', cn: '熟能生巧。', author: '谚语' },
  { id: 3, en: 'A journey of a thousand miles begins with a single step.', cn: '千里之行，始于足下。', author: '老子' },
  { id: 4, en: 'Learning never exhausts the mind.', cn: '学无止境。', author: 'Leonardo da Vinci' },
  { id: 5, en: 'The limits of my language mean the limits of my world.', cn: '我语言的界限，就是我世界的界限。', author: 'Wittgenstein' },
  { id: 6, en: 'Live as if you were to die tomorrow. Learn as if you were to live forever.', cn: '如同明日将死般生活，如同永远不死般学习。', author: 'Gandhi' },
  { id: 7, en: 'Mistakes are proof that you are trying.', cn: '犯错证明你在尝试。', author: '佚名' },
  { id: 8, en: 'The expert in anything was once a beginner.', cn: '任何领域的专家都曾是初学者。', author: 'Helen Hayes' },
  { id: 9, en: 'Slow progress is still progress.', cn: '慢一点的进步也是进步。', author: '佚名' },
  { id: 10, en: 'There is no substitute for hard work.', cn: '努力没有替代品。', author: 'Thomas Edison' },
]
